// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH90Sc5wOGGbvJpj0-jOFYHZirnLMlhe4',
    appId: '1:561726455254:web:4191cfbf955006aaca3877',
    messagingSenderId: '561726455254',
    projectId: 'trinetra-fitness',
    authDomain: 'trinetra-fitness.firebaseapp.com',
    storageBucket: 'trinetra-fitness.appspot.com',
    measurementId: 'G-RWY2CS30B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKszIt3lSmy0dLL_Zu1UMNEP6NORU0XsQ',
    appId: '1:561726455254:android:f9ebefc775bc0ee3ca3877',
    messagingSenderId: '561726455254',
    projectId: 'trinetra-fitness',
    storageBucket: 'trinetra-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoOxLvqYAtap-cRx7KmT-pKUvcwqHYE4Q',
    appId: '1:561726455254:ios:0766a85b9340fb95ca3877',
    messagingSenderId: '561726455254',
    projectId: 'trinetra-fitness',
    storageBucket: 'trinetra-fitness.appspot.com',
    iosClientId: '561726455254-43r8a3pb8q5dv3gk1u4f7mluurqrk6eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.trinetra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoOxLvqYAtap-cRx7KmT-pKUvcwqHYE4Q',
    appId: '1:561726455254:ios:0766a85b9340fb95ca3877',
    messagingSenderId: '561726455254',
    projectId: 'trinetra-fitness',
    storageBucket: 'trinetra-fitness.appspot.com',
    iosClientId: '561726455254-43r8a3pb8q5dv3gk1u4f7mluurqrk6eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.trinetra',
  );
}
