// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVB1SLbEO-LYEARt51GcD97CfYGVr8fFI',
    appId: '1:302475697728:web:e3ada96d2774543df289a5',
    messagingSenderId: '302475697728',
    projectId: 'trinetra-8cc8d',
    authDomain: 'trinetra-8cc8d.firebaseapp.com',
    storageBucket: 'trinetra-8cc8d.appspot.com',
    measurementId: 'G-MSN6GLF3PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrV43M5GwywCmlMhYhkMCwvTlGQI08wwg',
    appId: '1:302475697728:android:897621a5bb0f7eb6f289a5',
    messagingSenderId: '302475697728',
    projectId: 'trinetra-8cc8d',
    storageBucket: 'trinetra-8cc8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzfHSuMoHlaZXJSNnNtp-Y_FTbZP7O-ic',
    appId: '1:302475697728:ios:eff6a6da31e3b94af289a5',
    messagingSenderId: '302475697728',
    projectId: 'trinetra-8cc8d',
    storageBucket: 'trinetra-8cc8d.appspot.com',
    iosClientId: '302475697728-fuupn0u8julmtt9udmrarv92lpj00qml.apps.googleusercontent.com',
    iosBundleId: 'com.example.trinetra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzfHSuMoHlaZXJSNnNtp-Y_FTbZP7O-ic',
    appId: '1:302475697728:ios:eff6a6da31e3b94af289a5',
    messagingSenderId: '302475697728',
    projectId: 'trinetra-8cc8d',
    storageBucket: 'trinetra-8cc8d.appspot.com',
    iosClientId: '302475697728-fuupn0u8julmtt9udmrarv92lpj00qml.apps.googleusercontent.com',
    iosBundleId: 'com.example.trinetra',
  );
}
