// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiopeEqdswIfVrzu_WUAfLHQOO6krgUH4',
    appId: '1:842183685538:web:2b2032ead863856c72aefb',
    messagingSenderId: '842183685538',
    projectId: 'trinetra-flutter',
    authDomain: 'trinetra-flutter.firebaseapp.com',
    storageBucket: 'trinetra-flutter.appspot.com',
    measurementId: 'G-16WFX5FMSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmBr6ITfjjM-I3cyy3fbtv-BzHo_C35t4',
    appId: '1:842183685538:android:8b6d279928548b4072aefb',
    messagingSenderId: '842183685538',
    projectId: 'trinetra-flutter',
    storageBucket: 'trinetra-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxgxg83UNdNXT4kM5QSrYsZ6W5A4WOtts',
    appId: '1:842183685538:ios:aadf9ef4f601dc2672aefb',
    messagingSenderId: '842183685538',
    projectId: 'trinetra-flutter',
    storageBucket: 'trinetra-flutter.appspot.com',
    iosClientId: '842183685538-6ta5fdbh7nl202fn085sourn3etar8i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.trinetra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxgxg83UNdNXT4kM5QSrYsZ6W5A4WOtts',
    appId: '1:842183685538:ios:aadf9ef4f601dc2672aefb',
    messagingSenderId: '842183685538',
    projectId: 'trinetra-flutter',
    storageBucket: 'trinetra-flutter.appspot.com',
    iosClientId: '842183685538-6ta5fdbh7nl202fn085sourn3etar8i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.trinetra',
  );
}
